spring:
  application:
    name: file-service
  cloud:
    consul:
      host: consul
      port: 1801
      discovery:
        enabled: ${CONSUL_ENABLED:true}
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-1
        health-check-path: /health
        health-check-interval: 15s

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}