spring:
  application:
    name: lms-service
  datasource:
    url: jdbc:postgresql://localhost:1800/lms_db
    username: lms_user
    password: lms_password
  sql:
    init:
      mode: always # do never after first time create
  jpa:
    hibernate:
      ddl-auto: create # do none after first time create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cloud:
    gateway:
      routes:
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
    consul:
      host: localhost
      port: 1801
      discovery:
        enabled: ${CONSUL_ENABLED:true}
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-1
        health-check-path: /actuator/health
        health-check-interval: 15s

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS