spring:
  application:
    name: lms-service
  datasource:
    url: jdbc:postgresql://${LMS_DB_HOST:localhost}:${LMS_DB_PORT:5433}/${LMS_DB_NAME:lms-db}
    username: ${LMS_DB_USER:user}
    password: ${LMS_DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cloud:
    consul:
      host: ${LMS_CONSUL_ADDRESS:consul}
      port: 8500
      discovery:
        enabled: ${CONSUL_ENABLED:true}
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-1
        health-check-path: /actuator/health
        health-check-interval: 15s

server:
  port: ${LMS_PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS