spring:
  application:
    name: lms-service
  datasource:
    url: jdbc:postgresql://localhost:5433/lms_db
    username: lms_user
    password: lms_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: ${CONSUL_ENABLED:true}
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-1
        health-check-path: /actuator/health
        health-check-interval: 15s

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS