spring:
  application:
    name: email-service
  cloud:
    consul:
      host: consul
      port: 1801
      discovery:
        enabled: ${CONSUL_ENABLED:true}
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}-1
        health-check-path: /health
        health-check-interval: 15s

  mail:
    host: smtp.gmail.com
    port: 587
    username: tktvalhalla@gmail.com
    password: yatk jypb vdpy hdui
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
