spring.application.name=celestix
server.port=9555

# ===============================
# H2 DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/celestix_db_final?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql

# JPA & Hibernate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=QWcSdXNp2gTo6CyJuMxCDD18I7zx4aD0t2UmWoV+u9Y=
cors.allowed-origins=https://celestix-frontend-uit.vercel.app,http://localhost:9554,http://localhost:4173,http://localhost:5177,http://47.130.149.164:4173,http://47.130.149.164:8080

cloudinary.cloud.name=dsylx9zse
cloudinary.api.key=323724637428716
cloudinary.api.secret=ObkjrGOodGjUiw2IFLjCEPJOksE

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=celestix118@gmail.com
spring.mail.password=dfbx rnsq iykn sdvt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# CMS Service Configuration
cms.base-url=http://localhost:4001